[defaults]
limit           = 20                                # max articles per feed
max_image_width = 460                               # resize wider images to this

[[feeds]]
url   = "https://hnrss.org/newest?points=100"
